[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "mutagen>=1.47.0",
    "pygame>=2.6.1",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
    "yt-dlp>=2025.9.23",
]
